# Generated by Django 4.0.6 on 2022-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
